<a href="https://colab.research.google.com/github/CE334/CE334_230445_Harsh_gupta/blob/main/CE334_LAB0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 0

### Importing Libraries

In [252]:
import numpy as np
import pandas as pd

### Answer 1

In [253]:
# 1. Create a row and column vector using the input method and manually.
# Manual
row_vec = np.array([1, 2, 3])
col_vec = np.array([4, 5, 6]).reshape(-1, 1)

# Input method
# row_vec = np.array([float(x) for x in input("Enter row vector elements(space-separated): ").split()])
# col_vec = row_vec_input.reshape(-1, 1)

### Answer 2

In [254]:
# 2. Create a matrix (5x5) manually and via input, and save it as 'a'.
# Manual
a = np.array([
    [1, 0, 0, 0, 0],
    [0, 2, 0, 0, 0],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 4, 0],
    [0, 0, 0, 0, 5]
])

# Input method
# el = [float(x) for x in input("Enter 25 elements for 5x5 matrix: ").split()]
# a = np.array(el).reshape(5, 5)

print('Matrix:')
print(a)

Matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Answer 3

In [255]:
# 3. 3rd row out of the matrix
third_row = a[2, :]
print(f'third_row: {third_row}')

third_row: [0 0 3 0 0]


### Answer 4

In [256]:
# 4. 4th column out of the matrix
fourth_col = a[:, 3]
print(f'fourth_col: {fourth_col}')

fourth_col: [0 0 0 4 0]


### Answer 5

In [257]:
# 5. Sort the matrix row-wise and column-wise.
sorted_row = np.sort(a, axis=1)
print('Sorted row-wise:')
print(sorted_row)
sorted_col = np.sort(a, axis=0)
print('\nSorted col-wise:')
print(sorted_col)

Sorted row-wise:
[[0 0 0 0 1]
 [0 0 0 0 2]
 [0 0 0 0 3]
 [0 0 0 0 4]
 [0 0 0 0 5]]

Sorted col-wise:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 2 3 4 5]]


### Answer 6

In [258]:
# 6. For loop: if element > 2, multiply by 10, save as 'b'.
b = a.copy().astype(float)
rows, cols = b.shape
for i in range(rows):
    for j in range(cols):
        if b[i, j] > 2:
            b[i, j] *= 10

print('New Matrix b:')
print(b)

New Matrix b:
[[ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


### Answer 7

In [259]:
# 7. Add matrices a and b.
sum_ab = a + b
print('a+b =')
print(sum_ab)

a+b =
[[ 2.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.]
 [ 0.  0. 33.  0.  0.]
 [ 0.  0.  0. 44.  0.]
 [ 0.  0.  0.  0. 55.]]


### Answer 8

In [260]:
# 8. Subtract matrix b from a.
diff_ab = a - b
print('a-b =')
print(diff_ab)

a-b =
[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0. -27.   0.   0.]
 [  0.   0.   0. -36.   0.]
 [  0.   0.   0.   0. -45.]]


### Answer 9

In [261]:
# 9. Multiply matrix a by b element-wise and using matrix multiplication.
elem_mult = a * b
matrix_mult = a @ b
print('element-wise multiplication:')
print(elem_mult)
print('\nmatrix multiplication:')
print(matrix_mult)

element-wise multiplication:
[[  1.   0.   0.   0.   0.]
 [  0.   4.   0.   0.   0.]
 [  0.   0.  90.   0.   0.]
 [  0.   0.   0. 160.   0.]
 [  0.   0.   0.   0. 250.]]

matrix multiplication:
[[  1.   0.   0.   0.   0.]
 [  0.   4.   0.   0.   0.]
 [  0.   0.  90.   0.   0.]
 [  0.   0.   0. 160.   0.]
 [  0.   0.   0.   0. 250.]]


### Answer 10

In [262]:
# 10. Divide each element of matrices a and b by 18.
a = a / 18
print(f'a/18=\n{a}\n')
b = b / 18
print(f'b/18=\n{b}')

a/18=
[[0.05555556 0.         0.         0.         0.        ]
 [0.         0.11111111 0.         0.         0.        ]
 [0.         0.         0.16666667 0.         0.        ]
 [0.         0.         0.         0.22222222 0.        ]
 [0.         0.         0.         0.         0.27777778]]

b/18=
[[0.05555556 0.         0.         0.         0.        ]
 [0.         0.11111111 0.         0.         0.        ]
 [0.         0.         1.66666667 0.         0.        ]
 [0.         0.         0.         2.22222222 0.        ]
 [0.         0.         0.         0.         2.77777778]]


### Answer 11

In [263]:
# 11. Inverse, rank, condition number, SVD, and norm.
inv_a = np.linalg.inv(a)
print('inverse of a:')
print(inv_a)

rank_a = np.linalg.matrix_rank(a)
print(f'\nrank= {rank_a}')

cond_a = np.linalg.cond(a)
print(f'condition number= {cond_a}\n')

u, s, vh = np.linalg.svd(a)
print('U=')
print(u)
print('\nSigma=')
print(np.diag(s))
print('\nVT=')
print(vh)

norm_a = np.linalg.norm(a)
print(f'\nnorm= {norm_a}')

inverse of a:
[[18.   0.   0.   0.   0. ]
 [ 0.   9.   0.   0.   0. ]
 [ 0.   0.   6.   0.   0. ]
 [ 0.   0.   0.   4.5  0. ]
 [ 0.   0.   0.   0.   3.6]]

rank= 5
condition number= 5.000000000000001

U=
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

Sigma=
[[0.27777778 0.         0.         0.         0.        ]
 [0.         0.22222222 0.         0.         0.        ]
 [0.         0.         0.16666667 0.         0.        ]
 [0.         0.         0.         0.11111111 0.        ]
 [0.         0.         0.         0.         0.05555556]]

VT=
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

norm= 0.41201102706087017


### Answer 12

In [264]:
# 12. Norm, inner product, and outer product of the column vector.
v = col_vec
v_norm = np.linalg.norm(v)
print(f'norm= {v_norm}\n')

v_inner = np.dot(v.T, v).item()
print(f'inner product= {v_inner}\n')

v_outer = np.outer(v, v)
print(f'outer product= \n{v_outer}')

norm= 8.774964387392123

inner product= 77

outer product= 
[[16 20 24]
 [20 25 30]
 [24 30 36]]


### Answer 13

In [265]:
# 13. Derivative function with forward, backward, and central methods
def derivative(f, x, method='central', h=0.01):
    if method == 'forward':
        return (f(x + h) - f(x)) / h
    elif method == 'backward':
        return (f(x) - f(x - h)) / h
    elif method == 'central':
        return (f(x + h) - f(x - h)) / (2 * h)
    else:
        raise ValueError("Method not found")

# Finding derivative at x = 0.5
exp_der = derivative(np.exp, 0.5)
cos_der = derivative(np.cos, 0.5)
print(f"Exp derivative at 0.5: {exp_der}")
print(f"Cos derivative at 0.5: {cos_der}")

Exp derivative at 0.5: 1.648748749525375
Cos derivative at 0.5: -0.4794175482185081


### Answer 14

In [266]:
# 14. Read AWS Data as .csv file using Pandas
df = pd.read_excel('AWS.xlsx')
df.head()

created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15